### ISSUE TITLE
Not working in my Jellyfin install

### ISSUE THREAD

**Issue by felipemarinho97** [LizardByte/Themerr-jellyfin#296]
### Describe the Bug

The plugin can`t find theme songs. My jellyfin is pt-BR (the translations are missing).
![2024-05-10-16-17-tv darklyn org](https://github.com/LizardByte/Themerr-jellyfin/assets/20695061/ffd3f229-5a4a-488e-bd28-fedebcd651b1)

### Additional Context

Logs:
```
[15:38:06] [INF] [43] Jellyfin.Plugin.Themerr.ScheduledTasks.ThemerrTasks: Starting plugin, Downloading supported Theme Songs...
[15:38:07] [WRN] [43] Jellyfin.Plugin.Themerr.ThemerrManager: Missing from ThemerrDB: O Despertar de uma Paixão, contribute:
  https://github.com/LizardByte/ThemerrDB/issues/new?assignees=&labels=request-theme&template=theme.yml&title=[MOVIE]:%20O%20Despertar%20de%20uma%20Paixão%20(2006)&database_url=https://www.themoviedb.org/movie/14202
System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Jellyfin.Plugin.Themerr.ThemerrManager.GetYoutubeThemeUrl(String themerrDbUrl, BaseItem item)
[15:38:37] [WRN] [43] Jellyfin.Plugin.Themerr.ThemerrManager: Missing from ThemerrDB: Sou Louco Por Você, contribute:
  https://github.com/LizardByte/ThemerrDB/issues/new?assignees=&labels=request-theme&template=theme.yml&title=[MOVIE]:%20Sou%20Louco%20Por%20Você%20(2012)&database_url=https://www.themoviedb.org/movie/109689
System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Jellyfin.Plugin.Themerr.ThemerrManager.GetYoutubeThemeUrl(String themerrDbUrl, BaseItem item)
[15:39:08] [WRN] [43] Jellyfin.Plugin.Themerr.ThemerrManager: Missing from ThemerrDB: A Árvore do Amor, contribute:
  https://github.com/LizardByte/ThemerrDB/issues/new?assignees=&labels=request-theme&template=theme.yml&title=[MOVIE]:%20A%20Árvore%20do%20Amor%20(2010)&database_url=https://www.themoviedb.org/movie/50542
System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Jellyfin.Plugin.Themerr.ThemerrManager.GetYoutubeThemeUrl(String themerrDbUrl, BaseItem item)
[15:39:38] [WRN] [43] Jellyfin.Plugin.Themerr.ThemerrManager: Missing from ThemerrDB: A Pior Pessoa do Mundo, contribute:
  https://github.com/LizardByte/ThemerrDB/issues/new?assignees=&labels=request-theme&template=theme.yml&title=[MOVIE]:%20A%20Pior%20Pessoa%20do%20Mundo%20(2021)&database_url=https://www.themoviedb.org/movie/660120
System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Jellyfin.Plugin.Themerr.ThemerrManager.GetYoutubeThemeUrl(String themerrDbUrl, BaseItem item)
[15:41:09] [WRN] [43] Jellyfin.Plugin.Themerr.ThemerrManager: Missing from ThemerrDB: Mommy, contribute:
  https://github.com/LizardByte/ThemerrDB/issues/new?assignees=&labels=request-theme&template=theme.yml&title=[MOVIE]:%20Mommy%20(2014)&database_url=https://www.themoviedb.org/movie/265177
System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Jellyfin.Plugin.Themerr.ThemerrManager.GetYoutubeThemeUrl(String themerrDbUrl, BaseItem item)```



More logs:

   
```[16:15:45] [INF] [19] Jellyfin.Plugin.Themerr.Api.ThemerrController: Server culture: pt-BR
[16:15:45] [WRN] [19] Jellyfin.Plugin.Themerr.Api.ThemerrController: Locale resource does not exist: Jellyfin.Plugin.Themerr.Locale.pt_BR.json
[16:15:45] [WRN] [19] Jellyfin.Plugin.Themerr.Api.ThemerrController: Locale resource does not exist: Jellyfin.Plugin.Themerr.Locale.pt.json
[16:15:46] [INF] [40] Jellyfin.Plugin.Themerr.Api.ThemerrController: Progress Items: {"items":[{"name":"A Árvore do Amor","id":"075c1889-db4e-f8e7-daba-377a381c3e6b","issue_url":"https://github.com/LizardByte/ThemerrDB/issues/new?assignees=&labels=request-theme&template=theme.yml&title=[MOVIE]:%20A%20Árvore%20do%20Amor%20(2010)&database_url=https://www.themoviedb.org/movie/50542","theme_provider":null,"type":"Movie","year":2010},{"name":"A Baleia","id":"80161451-0d55-dd60-1b0c-2ffca36aef24","issue_url":"https://github.com/LizardByte/ThemerrDB/issues/new?assignees=&labels=request-theme&template=theme.yml&title=[MOVIE]:%20A%20Baleia%20(2022)&database_url=https://www.themoviedb.org/movie/785084","theme_provider":null,"type":"Movie","year":2022},{"name":"A Pior Pessoa do Mundo","id":"0e097417-3246-9685-812d-604a085f5123","issue_url":"https://github.com/LizardByte/ThemerrDB/issues/new?assignees=&labels=request-theme&template=theme.yml&title=[MOVIE]:%20A%20Pior%20Pessoa%20do%20Mundo%20(2021)&database_url=https://www.themoviedb.org/movie/660120","theme_provider":null,"type":"Movie","year":2021},{"name":"A Sociedade da Neve","id":"c388bdb7-976e-c3ba-519b-347329e9b2fa","issue_url":"https://github.com/LizardByte/ThemerrDB/issues/new?assignees=&labels=request-theme&template=theme.yml&title=[MOVIE]:%20A%20Sociedade%20da%20Neve%20(2023)&database_url=https://www.themoviedb.org/movie/906126","theme_provider":null,"type":"Movie","year":2023},{"name":"Ahsoka","id":"50a5cd45-4f13-c970-aa4b-fedea3638f8d","issue_url":"https://github.com/LizardByte/ThemerrDB/issues/new?assignees=&labels=request-theme&template=theme.yml&title=[TV SHOW]:%20Ahsoka%20(2023)&database_url=https://www.themoviedb.org/tv/114461","theme_provider":null,"type":"Series","year":2023},{"name":"Amnésia","id":"94ea2869-9297-6413-812a-327fed1802da","issue_url":"https://github.com/LizardByte/ThemerrDB/issues/new?assignees=&labels=request-theme&template=theme.yml&title=[MOVIE]:%20Amnésia%20(2000)&database_url=https://www.themoviedb.org/movie/77","theme_provider":null,"type":"Movie","year":2000},{"name":"Andrei Rublev","id":"c38e8c59-6cac-e38d-a8c0-12d36795f839","issue_url":"https://github.com/LizardByte/ThemerrDB/issues/new?assignees=&labels=request-theme&template=theme.yml&title=[MOVIE]:%20Andrei%20Rublev%20(1966)&database_url=https://www.themoviedb.org/movie/895","theme_provider":null,"type":"Movie","year":1966},{"name":"Barbie","id":"05879b5d-ac54-996b-41c5-798a7ff88baa","issue_url":"https://github.com/LizardByte/ThemerrDB/issues/new?assignees=&labels=request-theme&template=theme.yml&title=[MOVIE]:%20Barbie%20(2023)&database_url=https://www.themoviedb.org/movie/346698","theme_provider":null,"type":"Movie","year":2023},{"name":"Ben-Hur","id":"c1dc96f7-4272-20b5-0d51-37646abdc37a","issue_url":"https://github.com/LizardByte/ThemerrDB/issues/new?assignees=&labels=request-theme&template=theme.yml&title=[MOVIE]:%20Ben-Hur%20(1959)&database_url=https://www.themoviedb.org/movie/665","theme_provider":null,"type":"Movie","year":1959},{"name":"Blade II: O Caçador de Vampiros","id":"22ed2f8d-29ae-9480-9687-eb797a562820","issue_url":"https://github.com/LizardByte/ThemerrDB/issues/new?assignees=&labels=request-theme&template=theme.yml&title=[MOVIE]:%20Blade%20II:%20O%20Caçador%20de%20Vampiros%20(2002)&database_url=https://www.themoviedb.org/movie/36586","theme_provider":null,"type":"Movie","year":2002},{"name":"Bob Marley: One Love","id":"c722cd5e-7fbe-d4a3-f0e8-01b6d37c5f00","issue_url":"https://github.com/LizardByte/ThemerrDB/issues/new?assignees=&labels=request-theme&template=theme.yml&title=[MOVIE]:%20Bob%20Marley:%20One%20Love%20(2024)&database_url=https://www.themoviedb.org/movie/802219","theme_provider":null,"type":"Movie","year":2024},{"name":"Cartas de Iwo Jima","id":"2b075921-c16d-7d74-5f9c-aaa32899808d","issue_url":"https://github.com/LizardByte/ThemerrDB/issues/new?assignees=&labels=request-theme&template=theme.yml&title=[MOVIE]:%20Cartas%20de%20Iwo%20Jima%20(2006)&database_url=https://www.themoviedb.org/movie/1251","theme_provider":null,"type":"Movie","year":2006},{"name":"Cidadão Kane","id":"52393ac3-4901-6bc0-404f-54a9fa1990c3","issue_url":"https://github.com/LizardByte/ThemerrDB/issues/new?assignees=&labels=request-theme&template=theme.yml&title=[MOVIE]:%20Cidadão%20Kane%20(1941)&database_url=https://www.themoviedb.org/movie/15","theme_provider":null,"type":"Movie","year":1941}[...]```

**Comment by ReenigneArcher** [comment]
It looks like your access to https://app.lizardbyte.dev/ThemerrDB is possibly being blocked?

**Comment by ReenigneArcher** [comment]
I have merged a few things to help, but it doesn't address the main issue here.

1. Your language is now part of the project.
2. The UI should fall back to english if the user's locale is not localized in the project.

**Comment by felipemarinho97** [comment]
@ReenigneArcher I just updated the plugin to test your changes but my Jellyfin updated to 10.9.1 and the plugin does not work anymore. See #310.

**Comment by ReenigneArcher** [comment]
Okay, so the "exceptions" in your log are not errors as far as I can tell.

I might need to improve the logging, but those just indicate that those items are not in the database.

For example, I get the following in my test server.

```txt
[19:17:31] [WRN] [19] Jellyfin.Plugin.Themerr.ThemerrManager: Missing from ThemerrDB: Ghost Rider, contribute:
  https://github.com/LizardByte/ThemerrDB/issues/new?assignees=&labels=request-theme&template=theme.yml&title=[MOVIE]:%20Ghost%20Rider%20(2007)&database_url=https://www.themoviedb.org/movie/1250
System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Jellyfin.Plugin.Themerr.ThemerrManager.GetYoutubeThemeUrl(String themerrDbUrl, BaseItem item)
```

As for why Whiplash (2014) is not being downloaded, I can't tell from your logs.

I'm going to be releasing #314 soon, at which point I would suggest trying to see if anything in that version fixes things for you.

**Comment by ReenigneArcher** [comment]
@felipemarinho97 any luck with the latest version?

**Comment by ReenigneArcher** [comment]
Closing due to no response.
